theme: jekyll-theme-hacker

# Site
name: 'Joo's Blog'
description: 'Professional Engineer'
meta_description: 'JAVA'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/joo/'
google_analytics: ''
disqus: ''
mailchimp-list: ''

# Authors
authors:
  sal:
    name: joohyung park
    display_name: joohyung park
    gravatar: 
    email: joohyung1002@naver.com
    web: https://joope.github.io
    description: "skill Hub"
